/* Generated By:JavaCC: Do not edit this line. CNFParserTptpConstants.java */
package thProver.parserTptp;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CNFParserTptpConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int VLINE = 6;
  /** RegularExpression Id. */
  int NOT = 7;
  /** RegularExpression Id. */
  int COMMA = 8;
  /** RegularExpression Id. */
  int LPAR = 9;
  /** RegularExpression Id. */
  int RPAR = 10;
  /** RegularExpression Id. */
  int DOT = 11;
  /** RegularExpression Id. */
  int SEMICOLON = 12;
  /** RegularExpression Id. */
  int PREC = 13;
  /** RegularExpression Id. */
  int RANGLEPAR = 14;
  /** RegularExpression Id. */
  int WEIGHTS = 15;
  /** RegularExpression Id. */
  int WEIGHTVARS = 16;
  /** RegularExpression Id. */
  int EQUALS = 17;
  /** RegularExpression Id. */
  int LOWER_WORD = 18;
  /** RegularExpression Id. */
  int UPPER_WORD = 19;
  /** RegularExpression Id. */
  int SINGLE_QUOTED = 20;
  /** RegularExpression Id. */
  int LOWER_ALFA = 21;
  /** RegularExpression Id. */
  int UPPER_ALFA = 22;
  /** RegularExpression Id. */
  int DOLLAR_LOWER_ALFA = 23;
  /** RegularExpression Id. */
  int DOLLAR_UPPER_ALFA = 24;
  /** RegularExpression Id. */
  int ALFA_NUMERIC = 25;
  /** RegularExpression Id. */
  int DEF_SYS = 26;
  /** RegularExpression Id. */
  int UNDERSCORE = 27;
  /** RegularExpression Id. */
  int SINGLE_QUOTE = 28;
  /** RegularExpression Id. */
  int SQ_CHAR = 29;
  /** RegularExpression Id. */
  int INTEGER = 30;
  /** RegularExpression Id. */
  int SIGNED_INTEGER = 31;
  /** RegularExpression Id. */
  int DECIMAL = 32;
  /** RegularExpression Id. */
  int SIGN = 33;
  /** RegularExpression Id. */
  int NUMERIC = 34;
  /** RegularExpression Id. */
  int ZERO_NUMERIC = 35;
  /** RegularExpression Id. */
  int NON_ZERO_NUMERIC = 36;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "\"|\"",
    "\"~\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\".\"",
    "\";\"",
    "\"prec:\"",
    "\">\"",
    "\"weights:\"",
    "\"weightVars:\"",
    "\"=\"",
    "<LOWER_WORD>",
    "<UPPER_WORD>",
    "<SINGLE_QUOTED>",
    "<LOWER_ALFA>",
    "<UPPER_ALFA>",
    "<DOLLAR_LOWER_ALFA>",
    "<DOLLAR_UPPER_ALFA>",
    "<ALFA_NUMERIC>",
    "<DEF_SYS>",
    "\"_\"",
    "\"\\\'\"",
    "<SQ_CHAR>",
    "<INTEGER>",
    "<SIGNED_INTEGER>",
    "<DECIMAL>",
    "<SIGN>",
    "<NUMERIC>",
    "<ZERO_NUMERIC>",
    "<NON_ZERO_NUMERIC>",
  };

}
