/* Generated By:JavaCC: Do not edit this line. CNFParserConstants.java */
package thProver.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CNFParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OR = 6;
  /** RegularExpression Id. */
  int PREDICATE = 7;
  /** RegularExpression Id. */
  int SYMBOL = 8;
  /** RegularExpression Id. */
  int COMMA = 9;
  /** RegularExpression Id. */
  int SEMICOLON = 10;
  /** RegularExpression Id. */
  int LPAR = 11;
  /** RegularExpression Id. */
  int RPAR = 12;
  /** RegularExpression Id. */
  int NOT = 13;
  /** RegularExpression Id. */
  int CONST = 14;
  /** RegularExpression Id. */
  int PREC = 15;
  /** RegularExpression Id. */
  int RANGLEPAR = 16;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "<token of kind 5>",
    "\"|\"",
    "<PREDICATE>",
    "<SYMBOL>",
    "\",\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "<NOT>",
    "\"const:\"",
    "\"prec:\"",
    "\">\"",
  };

}
