/* Generated By:JavaCC: Do not edit this line. CNFParserConstants.java */
package thProver.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CNFParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OR = 6;
  /** RegularExpression Id. */
  int INTEGER = 7;
  /** RegularExpression Id. */
  int PREDICATE = 8;
  /** RegularExpression Id. */
  int SYMBOL = 9;
  /** RegularExpression Id. */
  int COMMA = 10;
  /** RegularExpression Id. */
  int SEMICOLON = 11;
  /** RegularExpression Id. */
  int LPAR = 12;
  /** RegularExpression Id. */
  int RPAR = 13;
  /** RegularExpression Id. */
  int NOT = 14;
  /** RegularExpression Id. */
  int CONST = 15;
  /** RegularExpression Id. */
  int PREC = 16;
  /** RegularExpression Id. */
  int RANGLEPAR = 17;
  /** RegularExpression Id. */
  int SOS = 18;
  /** RegularExpression Id. */
  int CLAUSES = 19;
  /** RegularExpression Id. */
  int WEIGHTS = 20;
  /** RegularExpression Id. */
  int WEIGHTVARS = 21;
  /** RegularExpression Id. */
  int EQUALS = 22;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "<token of kind 5>",
    "\"|\"",
    "<INTEGER>",
    "<PREDICATE>",
    "<SYMBOL>",
    "\",\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "<NOT>",
    "\"const:\"",
    "\"prec:\"",
    "\">\"",
    "\"sos:\"",
    "\"clauses:\"",
    "\"weights:\"",
    "\"weightVars:\"",
    "\"=\"",
  };

}
